import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[window]
padding = { x = 10, y = 10 }
title = "Alacritty"
dynamic_title = false
opacity = 0.6
blur = true

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 11.0
[env]
term = "xterm-256color"
